language: node_js
node_js:
  - "10"
install:
  - yarn install
script:
  - npm run build
deploy:
  provider: pages
  local_dir: dist/
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  name: brian
  email: ariutaiaa@gmail.com
  on:
    branch: master
